#!/usr/bin/env perl
use utf8;
binmode(STDOUT, ":utf8");

use strict;
use warnings;

use Mojo::Base -strict;
use Mojo::UserAgent;

my $keep_slashes = 0;

@ARGV = qw/please specify phrase/ if not @ARGV;

my $ua = Mojo::UserAgent->new;

for ( @ARGV ) {
    my $page = $ua->get("http://en.wiktionary.org/wiki/$_")->res->dom;
	my $span = $page->find('.IPA')->first;
	my $word;
	if ( $span ) {
		$word = $span->text;
		$word =~ s/\/(.*)\//$1/g if not $keep_slashes;
	}
	else {
	    $word = $_;
	}
	print "$word ";
}

print "\n";
